### ISSUE TITLE
Can't find language file

### ISSUE THREAD

**Issue by harryb** [Niambie/jfoobar#6] opened 2011-09-07 02:02 UTC
Note:  although diretory path says .. /j16/.., it's reallyu a Joomla 1.7 installaton, http://rc.hrpr.com/j16

Think part of this error condition is related to fact that I installed Jfoobar in environment where my Joomla instance and Mysql DB are installed on  separate physical servers.  Will try to verify on my local server which has both installed on same box.

PLG_SYSTEM_FILE_NOT_FOUND /home/halfvast/rc.hrpr.com/j16/components/com_hrtests/language/en-GBen-GB.com_jfoobars.ini
PLG_SYSTEM_FILE_NOT_FOUND /home/halfvast/rc.hrpr.com/j16/components/com_hrtests/language/en-GBen-GB.com_jfoobars.sys.ini
JInstaller: :Install: SQL File not found /home/halfvast/rc.hrpr.com/j16/administrator/components/com_hrtests/sql/install.mysql.utf8.sql
Component Install: SQL error file DB function reports no errors
PLG_SYSTEM_CREATE_MSG_DISCOVER_INSTALL_FAILED: 10007
PLG_SYSTEM_CREATE_INSTALL_EXTENSION_FAILED: component

**Comment by CristinaSolana** [comment] 2011-09-07 02:13
Hi Harry, where do you see this error, I assume upon creating custom component? I have a remote sql server I can test on as well.
Cheers,

Cristina Solana

## 

Pardon my brevity (and any errors in spelling or grammar), this was sent from my mobile device.

harryb reply@reply.github.com wrote:

Note: although diretory path says .. /j16/.., it's reallyu a Joomla 1.7 installaton, http://drc.hrpr.com/j16

Think part of this error condition is related to fact that I installed Jfoobar in environment where my Joomla instance and Mysql DB are installed on separate physical servers. Will try to verify on my local server which has both installed on same box.

PLG_SYSTEM_FILE_NOT_FOUND /home/halfvast/rc.hrpr.com/j16/components/com_hrtests/language/en-GBen-GB.com_jfoobars.ini
PLG_SYSTEM_FILE_NOT_FOUND /home/halfvast/rc.hrpr.com/j16/components/com_hrtests/language/en-GBen-GB.com_jfoobars.sys.ini
JInstaller: :Install: SQL File not found /home/halfvast/rc.hrpr.com/j16/administrator/components/com_hrtests/sql/install.mysql.utf8.sql
Component Install: SQL error file DB function reports no errors
PLG_SYSTEM_CREATE_MSG_DISCOVER_INSTALL_FAILED: 10007
PLG_SYSTEM_CREATE_INSTALL_EXTENSION_FAILED: component

## 

Reply to this email directly or view it on GitHub:
https://github.com/Niambie/jfoobar/issues/6

**Comment by AmyStephen** [comment] 2011-09-07 03:07
Harry - 

That error is happening when the rename files process is running. It first looks to ensure the expected file exists (the file named in your error message) - and then it renames it if it does. If it doesn't - this error presents.

So, what is apparently happening is the copy process failed. 

I'm using the JFile and JFolder API, so it is not immediately obvious why it would be failing.

Is there anything about your environment that other Joomla file handling has problems with? 

Do you think maybe it is permissions issues? (Maybe something I need to do to ensure permissions are correct?) The administrator/components/com_jfoobar/media/components folder must be readable by JFile/JFolder. Is there anything that you can see that would prevent that from happening?

Would you mind manually changing permissions to see if that "fixes" the problem (if so, I'd have to figure out how to really fix it.)

Backing up a step further -- are all the files from this link < https://github.com/Niambie/jfoobar/tree/master/media/components > properly installed at this location? -> administrator/components/com_jfoobar/media/components 

Thanks for your help and report.

**Comment by harryb** [comment] 2011-09-07 12:19
Here's the problem (I think)

PLG_SYSTEM_FILE_NOT_FOUND /home/halfvast/rc.hrpr.com/j16/components/com_mytests/language/**en-GB**en-GB.com_jfoobars.ini
PLG_SYSTEM_FILE_NOT_FOUND /home/halfvast/rc.hrpr.com/j16/components/com_mytests/language/**en-GB**en-GB.com_jfoobars.sys.ini

should be:

/home/halfvast/rc.hrpr.com/j16/components/com_mytests/language/**en-GB/**en-GB.com_jfoobars.ini
/home/halfvast/rc.hrpr.com/j16/components/com_mytests/language/**en-GB/**en-GB.com_jfoobars.sys.in

Path to language files is not being formed correctly.  Slash ( / ) missing between en-GB subdirectory and file names.

Maybe has to do with length and/or number of subdirectory levels in path??

**Comment by harryb** [comment] 2011-09-07 13:25
Installed fresh copies of Joomla 1.7 and JFoobar on my local server and got same results.  Local server is running Ubuntu Linux with local Mysql server and a number of other LAMP packages with no issues...see iist lof apps below:

It works!
This is the default web page for this server.  The following applications are available:

Drupal 6 
Drupal 7 
Joomla 1.7 
Zen Cart 
PHP Info 
Phpmyadmin 
Shell in a Box 
Webmin 
UMW Flowers - 2011 

Error messages from Joobar:

PLG_SYSTEM_FILE_NOT_FOUND /var/www/j17/components/com_hrtests/language/en-GBen-GB.com_jfoobars.ini
PLG_SYSTEM_FILE_NOT_FOUND /var/www/j17/components/com_hrtests/language/en-GBen-GB.com_jfoobars.sys.ini
JInstaller: :Install: SQL File not found /var/www/j17/administrator/components/com_hrtests/sql/install.mysql.utf8.sql
Component Install: SQL error file DB function reports no errors
PLG_SYSTEM_CREATE_MSG_DISCOVER_INSTALL_FAILED: 10001
PLG_SYSTEM_CREATE_INSTALL_EXTENSION_FAILED: component

**Comment by CristinaSolana** [comment] 2011-09-07 14:28
Clearly there is an issue with the path, I tested however and am not experiencing the issue on my local server. We'll keep looking.

**Comment by AmyStephen** [comment] 2011-09-07 17:34
Harry - 

Does this file exist? (with the slash)?

/var/www/j17/components/com_hrtests/language/en-GB/en-GB.com_jfoobars.sys.ini

Thanks.

**Comment by harryb** [comment] 2011-09-07 19:26
No.  Directory is empty except for index.html file..

**Comment by AmyStephen** [comment] 2011-09-08 04:20
OK - can you check in the administrator/components/com_jfoobar/media/components/site/components/com_jfoobar/language/enGB/ folder?

**Comment by harryb** [comment] 2011-09-08 13:35
Nothing there but index.html.  Is "..site/components/**com_jfoobar**/.." a typo?? 

"..site/components/**com_jfoobars**.." 

/var/www/j17/administrator/components/com_jfoobar/media/components/**site/components/com_jfoobars**/language/en-GB

**Comment by AmyStephen** [comment] 2011-09-08 17:36
Yes indeed, Harry, that was a type-o on my part.

The Joomla installer is not copying all of the source files to the proper location.

Can you try a couple of things:
1. Download a new zip (don't use the "package" but rather use a "download source" option.)
2. Try the install again and see if it copies this time (meaning maybe something got fixed.) 
3. If not, unzip into the tmp folder and install from that location and see if it copies the files.

I'm not up on permissions - maybe I have the wrong permissions set on the media folder? You are much better at those system things than I am -- maybe you can see something obvious in the permissions of the missing language files on the source.

I appreciate your patience on this.

**Comment by harryb** [comment] 2011-09-08 18:38
1 & 2. new zip from download source installed and functional on both my local and remote servers. Now have a component named HRTEST on botth.
1.  I'll try the jfoobar tar.gz file when I get time to make sure it's ok too.

.

**Comment by harryb** [comment] 2011-09-08 19:30
The tar.gz files are corrupted. Got same error with tar.gz files from "package" and "download source" options.  

Too bad, most of us Linux ;propheads have tar.gz  hardwired in our DNA and get really upset when it is misused and abused. ;)

BTW do you know if there's a patch that fixes Joomla 1.7 inability to change global config when using IE9 (Other than brute force command line editing)?

**Comment by AmyStephen** [comment] 2011-09-08 19:53
OK - now Cristina and I are seeing the same problem. 

I don't think the tar.gz is corrupt tho - because the files are on the source. 

I think it's Joomla - somehow it is not copying those files when you install the component using the tar.gz.

I'll do some more digging. Wish we could disable the tar.gz for now.

Thanks, Harry - we'll keep going on this now that we have it reproduced. Appreciate your help.

**Comment by AmyStephen** [comment] 2011-09-09 03:04
Reported the problem https://github.com/joomla/joomla-platform/issues/350

If you manually unzip this tar.gz file int the tmp folder, it can be installed using the "Installation Folder" option. 

I can see where the data is lost, but I am stumped as to why.

**Comment by AmyStephen** [comment] 2011-09-09 03:15
Also, sent a contact note to Github to see if we can disable the tar.gz until we can fix the problem in the J installer

**Comment by AmyStephen** [comment] 2011-09-09 05:16
The project is going to "mark this" as a known issue for now. After looking at the method where the issue is, I tend to agree that maybe we should see if others have issues with their packages on Github, too.

I added a warning to the readme that the tar.gz file should be unzipped into the tmp folder - and can then be installed using the folder option. Dumb, I know, but I can't offer a better option at this point.

Still hope we can at least turn off the tar.gz option - waiting to hear from github.

Going to close this for now (unless others have a better idea.)

Thanks Harry.

**Closed as completed by AmyStephen** 2011-09-09 05:16 UTC
